package com.netease.backend.db.common.proc;

import java.util.concurrent.ThreadFactory;


public class PoolThreadFactory implements ThreadFactory { 
	private String threadName = "thread generated by PoolThreadFactory";
	
	private boolean isDaemon = false;
	
    public PoolThreadFactory() {
		super();
	}


	public PoolThreadFactory(String threadName, boolean isDaemon) {
		super();
		this.threadName = threadName;
		this.isDaemon = isDaemon;
	}



	public Thread newThread(Runnable r) { 
        Thread thread = new Thread(r); 
        thread.setDaemon(isDaemon);
        thread.setName(threadName);
        return thread; 
    } 
} 